window.ERAS_DATA = [
  {
    id: 1,
    nameHe: "עשרה דורות מאדם עד נח",
    nameEn: "Ten Generations from Adam to Noah",
    startYear: 0,
    endYear: 2006,
    persons: [
      { id: "adam", nameHe: "אדם", nameEn: "Adam", birthYear: 1, deathYear: 930, title: "צדיק", summary: "", midrash: "", sources: "", image: null },
      { id: "shet", nameHe: "שת", nameEn: "Shet", birthYear: 130, deathYear: 1042, title: "צדיק", summary: "", midrash: "", sources: "", image: null },
      { id: "enosh", nameHe: "אנוש", nameEn: "Enosh", birthYear: 235, deathYear: 1140, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "kenan", nameHe: "קינן", nameEn: "Kenan", birthYear: 325, deathYear: 1235, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "mahalalel", nameHe: "מהללאל", nameEn: "Mahalalel", birthYear: 395, deathYear: 1290, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "yered", nameHe: "ירד", nameEn: "Yered", birthYear: 460, deathYear: 1422, title: "צדיק", summary: "", midrash: "", sources: "", image: null },
      { id: "chanoch", nameHe: "חנוך", nameEn: "Chanoch", birthYear: 622, deathYear: 987, title: "צדיק", summary: "", midrash: "", sources: "", image: null },
      { id: "mesushelach", nameHe: "מתושלח", nameEn: "Mesushelach", birthYear: 687, deathYear: 1656, title: "צדיק", summary: "", midrash: "", sources: "", image: null },
      { id: "lemech", nameHe: "למך", nameEn: "Lemech", birthYear: 874, deathYear: 1651, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "noach", nameHe: "נח", nameEn: "Noach", birthYear: 1056, deathYear: 2006, title: "צדיק", summary: "", midrash: "", sources: "", image: null },
    ],
    events: [
      { year: 0, descHe: "בריאת העולם (ספר בראשית)", descEn: "Creation of the world (Book of Genesis)" },
    ],
  },
  {
    id: 2,
    nameHe: "עשרה דורות מנח עד אברהם",
    nameEn: "Ten Generations from Noah to Abraham",
    startYear: 1056,
    endYear: 2123,
    persons: [
      { id: "noach", nameHe: "נח", nameEn: "Noach", birthYear: 1056, deathYear: 2006, title: "צדיק", summary: "", midrash: "", sources: "", image: null },
      { id: "shem", nameHe: "שם", nameEn: "Shem", birthYear: 1558, deathYear: 2158, title: "צדיק", summary: "", midrash: "", sources: "", image: null },
      { id: "arpachshad", nameHe: "ארפכשד", nameEn: "Arpachshad", birthYear: 1658, deathYear: 2096, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "shelach", nameHe: "שלח", nameEn: "Shelach", birthYear: 1693, deathYear: 2126, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "ever", nameHe: "עבר", nameEn: "Ever", birthYear: 1723, deathYear: 2187, title: "צדיק", summary: "", midrash: "", sources: "", image: null },
      { id: "peleg", nameHe: "פלג", nameEn: "Peleg", birthYear: 1757, deathYear: 1996, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "reu", nameHe: "רעו", nameEn: "Reu", birthYear: 1787, deathYear: 2026, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "serug", nameHe: "שרוג", nameEn: "Serug", birthYear: 1819, deathYear: 2049, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "nachor", nameHe: "נחור", nameEn: "Nachor", birthYear: 1849, deathYear: 1997, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "terach", nameHe: "תרח", nameEn: "Terach", birthYear: 1878, deathYear: 2083, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "avraham-avinu", nameHe: "אברהם אבינו", nameEn: "Avraham Avinu", birthYear: 1948, deathYear: 2123, title: "", summary: "", midrash: "", sources: "", image: null },
    ],
    events: [
      { year: 1656, descHe: "המבול על הארץ", descEn: "The Flood upon the earth" },
    ],
  },
  {
    id: 3,
    nameHe: "אבותנו ואמותנו הקדושים",
    nameEn: "Our Holy Patriarchs and Matriarchs",
    startYear: 1948,
    endYear: 2255,
    persons: [
      { id: "avraham-avinu", nameHe: "אברהם אבינו", nameEn: "Avraham Avinu", birthYear: 1948, deathYear: 2123, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "sarah-imenu", nameHe: "שרה אמנו", nameEn: "Sarah Imenu", birthYear: 1958, deathYear: 2085, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "yishmael", nameHe: "ישמעאל", nameEn: "Yishmael", birthYear: 2034, deathYear: 2171, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "yitzchak-avinu", nameHe: "יצחק אבינו", nameEn: "Yitzchak Avinu", birthYear: 2048, deathYear: 2228, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "rivkah-imenu", nameHe: "רבקה אמנו", nameEn: "Rivkah Imenu", birthYear: 2075, deathYear: 2207, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "yaakov-avinu", nameHe: "יעקב אבינו", nameEn: "Yaakov Avinu", birthYear: 2108, deathYear: 2255, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "esau", nameHe: "עשו", nameEn: "Esau", birthYear: 2108, deathYear: 2255, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "leah-imenu", nameHe: "לאה אמנו", nameEn: "Leah Imenu", birthYear: 2163, deathYear: 2216, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "rachel-imenu", nameHe: "רחל אמנו", nameEn: "Rachel Imenu", birthYear: 2163, deathYear: 2207, title: "", summary: "", midrash: "", sources: "", image: null },
    ],
    events: [
      { year: 1996, descHe: "דור הפלגה", descEn: "Generation of the Dispersion (Tower of Babel)" },
      { year: 1998, descHe: "אברהם בכבשן האש", descEn: "Avraham in the fiery furnace" },
      { year: 2000, descHe: "הפצת תורה", descEn: "Spreading of Torah" },
      { year: 2018, descHe: "ברית בין הבתרים", descEn: "Covenant Between the Parts" },
      { year: 2023, descHe: "יציאת אברהם מחרן לארץ ישראל", descEn: "Avraham leaves Charan for Eretz Yisrael" },
      { year: 2047, descHe: "הפיכת סדום", descEn: "Overthrow of Sodom" },
      { year: 2085, descHe: "פטירת שרה אמנו", descEn: "Death of Sarah Imenu" },
      { year: 2085, descHe: "עקידת יצחק", descEn: "Binding of Yitzchak (Akedah)" },
      { year: 2088, descHe: "חתונת יצחק עם רבקה", descEn: "Wedding of Yitzchak and Rivkah" },
      { year: 2123, descHe: "פטירת אברהם אבינו", descEn: "Death of Avraham Avinu" },
      { year: 2171, descHe: "יעקב מקבל הברכות מיצחק", descEn: "Yaakov receives Yitzchak's blessings" },
      { year: 2185, descHe: "ויצא יעקב לחרן בגיל 77", descEn: "Yaakov goes to Charan at age 77" },
      { year: 2192, descHe: "חתונת יעקב עם לאה ולאחר שבוע עם רחל", descEn: "Yaakov marries Leah and, a week later, Rachel" },
    ],
  },
  {
    id: 4,
    nameHe: "שבטי ישראל",
    nameEn: "Tribes of Israel",
    startYear: 2192,
    endYear: 2331,
    persons: [
      { id: "reuven-ben-yaakov", nameHe: "ראובן בן יעקב", nameEn: "Reuven ben Yaakov", birthYear: 2192, deathYear: 2317, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "shimon-ben-yaakov", nameHe: "שמעון בן יעקב", nameEn: "Shimon ben Yaakov", birthYear: 2193, deathYear: 2313, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "levi-ben-yaakov", nameHe: "לוי בן יעקב", nameEn: "Levi ben Yaakov", birthYear: 2194, deathYear: 2331, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "dan-ben-yaakov", nameHe: "דן בן יעקב", nameEn: "Dan ben Yaakov", birthYear: 2194, deathYear: 2321, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "naftali-ben-yaakov", nameHe: "נפתלי בן יעקב", nameEn: "Naftali ben Yaakov", birthYear: 2195, deathYear: 2327, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "yehudah-ben-yaakov", nameHe: "יהודה בן יעקב", nameEn: "Yehudah ben Yaakov", birthYear: 2195, deathYear: 2314, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "yissaskhar-ben-yaakov", nameHe: "יששכר בן יעקב", nameEn: "Yissaskhar ben Yaakov", birthYear: 2196, deathYear: 2318, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "gad-ben-yaakov", nameHe: "גד בן יעקב", nameEn: "Gad ben Yaakov", birthYear: 2196, deathYear: 2321, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "zevulun-ben-yaakov", nameHe: "זבולון בן יעקב", nameEn: "Zevulun ben Yaakov", birthYear: 2197, deathYear: 2321, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "asher-ben-yaakov", nameHe: "אשר בן יעקב", nameEn: "Asher ben Yaakov", birthYear: 2197, deathYear: 2320, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "yosef-ben-yaakov", nameHe: "יוסף בן יעקב", nameEn: "Yosef ben Yaakov", birthYear: 2199, deathYear: 2309, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "binyamin-ben-yaakov", nameHe: "בנימין בן יעקב", nameEn: "Binyamin ben Yaakov", birthYear: 2207, deathYear: 2318, title: "", summary: "", midrash: "", sources: "", image: null },
    ],
    events: [
      { year: 2207, descHe: "פטירת רחל אמנו", descEn: "Death of Rachel Imenu" },
    ],
  },
  {
    id: 5,
    nameHe: "גלות מצרים",
    nameEn: "Egyptian Exile",
    startYear: 2216,
    endYear: 2516,
    persons: [
      { id: "shloshim-shnot-shiabud", nameHe: "שלושים שנות שיעבוד", nameEn: "Shloshim Shnot Shiabud (Thirty Years of Servitude)", birthYear: 2331, deathYear: 2361, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "miriam-haneviah", nameHe: "מרים הנביאה", nameEn: "Miriam Haneviah", birthYear: 2361, deathYear: 2487, title: "נביאה", summary: "", midrash: "", sources: "", image: null },
      { id: "aharon-hakohen", nameHe: "אהרן הכהן", nameEn: "Aharon Hakohen", birthYear: 2365, deathYear: 2487, title: "כהן", summary: "", midrash: "", sources: "", image: null },
      { id: "moshe-rabbeinu", nameHe: "משה רבינו", nameEn: "Moshe Rabbeinu", birthYear: 2368, deathYear: 2488, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "yehoshua-bin-nun", nameHe: "יהושע בן נון", nameEn: "Yehoshua bin Nun", birthYear: 2406, deathYear: 2516, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "shnat-asser-hamakot", nameHe: "השנה של עשר המכות", nameEn: "The Year of the Ten Plagues", birthYear: 2447, deathYear: 2448, title: "", summary: "", midrash: "", sources: "", image: null },
    ],
    events: [
      { year: 2216, descHe: "מכירת יוסף בן 17", descEn: "Sale of Yosef at age 17" },
      { year: 2216, descHe: "פטירת לאה אמנו", descEn: "Death of Leah Imenu" },
      { year: 2228, descHe: "פטירת יצחק אבינו", descEn: "Death of Yitzchak Avinu" },
      { year: 2229, descHe: "יוסף פותר חלומות פרעה", descEn: "Yosef interprets Pharaoh's dreams" },
      { year: 2238, descHe: "מפגש יוסף עם אחיו ואביו", descEn: "Yosef reunites with his brothers and father" },
      { year: 2255, descHe: "פטירת יעקב אבינו", descEn: "Death of Yaakov Avinu" },
      { year: 2309, descHe: "פטירת יוסף (בן 110)", descEn: "Death of Yosef (age 110)" },
    ],
  },
  {
    id: 6,
    nameHe: "יציאת מצרים ודור המדבר",
    nameEn: "Exodus and the Wilderness Generation",
    startYear: 2448,
    endYear: 2488,
    persons: [],
    events: [
      { year: 2448, descHe: "יציאת מצרים", descEn: "The Exodus from Egypt" },
      { year: 2448, descHe: "קריעת ים סוף", descEn: "Splitting of the Sea of Reeds" },
      { year: 2448, descHe: "מתן תורה (עשרת הדברות)", descEn: "Giving of the Torah (Ten Commandments)" },
      { year: 2448, descHe: "חטא העגל ושבירת הלוחות", descEn: "Sin of the Golden Calf and breaking of the Tablets" },
      { year: 2449, descHe: "הקמת המשכן", descEn: "Establishment of the Mishkan" },
      { year: 2449, descHe: "חטא המרגלים", descEn: "Sin of the spies" },
      { year: 2487, descHe: "פטירת מרים ואהרן הכהן", descEn: "Death of Miriam and Aharon Hakohen" },
      { year: 2488, descHe: "פטירת משה רבינו", descEn: "Death of Moshe Rabbeinu" },
      { year: 2488, descHe: "עברו את הירדן", descEn: "They crossed the Jordan" },
    ],
  },
  {
    id: 7,
    nameHe: "כניסה לארץ ישראל וכיבוש על ידי יהושע",
    nameEn: "Entry to Eretz Yisrael and Conquest by Yehoshua",
    startYear: 2488,
    endYear: 2871,
    persons: [
      { id: "tekufat-sefer-yehoshua", nameHe: "תקופת ספר יהושע", nameEn: "Era of the Book of Yehoshua", birthYear: 2488, deathYear: 2516, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "kibush-haaretz", nameHe: "כיבוש הארץ", nameEn: "Kibush HaAretz (Conquest of the Land)", birthYear: 2488, deathYear: 2495, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "chilukat-eretz-yisrael-lashvatim", nameHe: "חלוקת ארץ ישראל לשבטים", nameEn: "Division of Eretz Yisrael among the tribes", birthYear: 2495, deathYear: 2502, title: "", summary: "", midrash: "", sources: "", image: null },
      { id: "mishkan-hashem-beshilo", nameHe: "משכן ה' בשילה", nameEn: "Mishkan of Hashem in Shiloh", birthYear: 2502, deathYear: 2871, title: "", summary: "", midrash: "", sources: "", image: null },
    ],
    events: [
      { year: 2488, descHe: "כניסה לארץ ישראל על ידי יהושע", descEn: "Entry into Eretz Yisrael by Yehoshua" },
      { year: 2515, descHe: "פטירת יהושע בן נון", descEn: "Death of Yehoshua bin Nun" },
    ],
  },
  {
    id: 8,
    nameHe: "תקופת השופטים",
    nameEn: "Period of the Judges",
    startYear: 2516,
    endYear: 2924,
    persons: [
      { id: "otniel-ben-kenaz", nameHe: "עתניאל בן קנז", nameEn: "Otniel ben Kenaz", birthYear: 2516, deathYear: 2556, title: "שופט", summary: "", midrash: "", sources: "", image: null },
      { id: "ehud-ben-gera", nameHe: "אהוד בן גרא", nameEn: "Ehud ben Gera", birthYear: 2556, deathYear: 2636, title: "שופט", summary: "", midrash: "", sources: "", image: null },
      { id: "shamgar-ben-anat", nameHe: "שמגר בן ענת", nameEn: "Shamgar ben Anat", birthYear: 2636, deathYear: 2636, title: "שופט", summary: "", midrash: "", sources: "", image: null },
      { id: "devorah-haneviah-u-varak-ben-avinoam", nameHe: "דבורה הנביאה וברק בן אבינועם", nameEn: "Devorah Haneviah and Barak ben Avinoam", birthYear: 2636, deathYear: 2676, title: "שופט/נביאה", summary: "", midrash: "", sources: "", image: null },
      { id: "gidon-ben-yoash", nameHe: "גדעון בן יהואש", nameEn: "Gidon ben Yoash", birthYear: 2676, deathYear: 2716, title: "שופט", summary: "", midrash: "", sources: "", image: null },
      { id: "avimelech-ben-gidon", nameHe: "אבימלך בן גדעון", nameEn: "Avimelech ben Gidon", birthYear: 2716, deathYear: 2719, title: "שופט", summary: "", midrash: "", sources: "", image: null },
      { id: "tola-ben-puah", nameHe: "תולע בן פואה", nameEn: "Tola ben Puah", birthYear: 2719, deathYear: 2742, title: "שופט", summary: "", midrash: "", sources: "", image: null },
      { id: "yair-hagiladi", nameHe: "יאיר הגלעדי", nameEn: "Yair Hagiladi", birthYear: 2742, deathYear: 2764, title: "שופט", summary: "", midrash: "", sources: "", image: null },
      { id: "yiftach-hagiladi", nameHe: "יפתח הגלעדי", nameEn: "Yiftach Hagiladi", birthYear: 2781, deathYear: 2787, title: "שופט", summary: "", midrash: "", sources: "", image: null },
      { id: "avtzan-mibeit-lechem", nameHe: "אבצן מבית לחם", nameEn: "Avtzan of Beit Lechem", birthYear: 2787, deathYear: 2793, title: "שופט", summary: "", midrash: "", sources: "", image: null },
      { id: "elon-hazevuloni", nameHe: "אילון הזבולוני", nameEn: "Elon HaZevuloni", birthYear: 2793, deathYear: 2803, title: "שופט", summary: "", midrash: "", sources: "", image: null },
      { id: "avdon-ben-hillel", nameHe: "עבדון בן הלל", nameEn: "Avdon ben Hillel", birthYear: 2803, deathYear: 2811, title: "שופט", summary: "", midrash: "", sources: "", image: null },
      { id: "shimshon", nameHe: "שמשון", nameEn: "Shimshon", birthYear: 2811, deathYear: 2831, title: "שופט", summary: "", midrash: "", sources: "", image: null },
      { id: "shmuel-hanavi", nameHe: "שמואל הנביא", nameEn: "Shmuel Hanavi", birthYear: 2830, deathYear: 2884, title: "נביא", summary: "", midrash: "", sources: "", image: null },
      { id: "eli-hakohen", nameHe: "עלי הכהן", nameEn: "Eli Hakohen", birthYear: 2831, deathYear: 2871, title: "כהן גדול", summary: "", midrash: "", sources: "", image: null },
      { id: "david-hamelech", nameHe: "דוד המלך", nameEn: "David Hamelech", birthYear: 2854, deathYear: 2924, title: "מלך", summary: "", midrash: "", sources: "", image: null },
    ],
    events: [],
  },

{
  id: "era-9-melachim-bayit-rishon",
  nameHe: "תקופת המלכים ובית ראשון",
  nameEn: "Period of the Kings and First Temple",
  startYear: 2881,
  endYear: 3338,
  persons: [
    { id: "shaul-hamelech", nameHe: "שאול המלך", nameEn: "King Saul", birthYear: 2881, deathYear: 2883, title: "King", summary: "", midrash: "", sources: "", image: null },
    { id: "shlomo-hamelech", nameHe: "שלמה המלך", nameEn: "King Solomon", birthYear: 2912, deathYear: 2964, title: "King", summary: "", midrash: "", sources: "", image: null },
    { id: "rechavam", nameHe: "רחבעם", nameEn: "Rehoboam", birthYear: 2964, deathYear: 2981, title: "King of Judah", summary: "", midrash: "", sources: "", image: null },
    { id: "yeravam-ben-navat", nameHe: "ירבעם בן נבט", nameEn: "Jeroboam ben Nebat", birthYear: 2964, deathYear: 2985, title: "King of Israel", summary: "", midrash: "", sources: "", image: null },
    { id: "aviyah-ben-rechavam", nameHe: "אביה בן רחבעם", nameEn: "Abijah ben Rehoboam", birthYear: 2981, deathYear: 2983, title: "King of Judah", summary: "", midrash: "", sources: "", image: null },
    { id: "asa-ben-aviyah", nameHe: "אסא בן אביה", nameEn: "Asa ben Abijah", birthYear: 2983, deathYear: 3024, title: "King of Judah", summary: "", midrash: "", sources: "", image: null },
    { id: "achav-ben-omri", nameHe: "אחאב בן עמרי", nameEn: "Ahab ben Omri", birthYear: 3021, deathYear: 3041, title: "King of Israel", summary: "", midrash: "", sources: "", image: null },
    { id: "yehoshafat-ben-asa", nameHe: "יהושפט בן אסא", nameEn: "Jehoshaphat ben Asa", birthYear: 3024, deathYear: 3047, title: "King of Judah", summary: "", midrash: "", sources: "", image: null },
    { id: "yehu-ben-nimshi", nameHe: "יהוא בן נמשי", nameEn: "Jehu ben Nimshi", birthYear: 3055, deathYear: 3083, title: "King of Israel", summary: "", midrash: "", sources: "", image: null },
    { id: "yoash-ben-achazyahu", nameHe: "יואש בן אחזיהו", nameEn: "Joash ben Ahaziah", birthYear: 3061, deathYear: 3100, title: "King of Judah", summary: "", midrash: "", sources: "", image: null },
    { id: "yeravam-ben-yoash", nameHe: "ירבעם בן יהואש", nameEn: "Jeroboam ben Joash", birthYear: 3114, deathYear: 3153, title: "King of Israel", summary: "", midrash: "", sources: "", image: null },
    { id: "uziyahu-ben-amatziah", nameHe: "עוזיהו בן אמיציה", nameEn: "Uzziah ben Amaziah", birthYear: 3115, deathYear: 3167, title: "King of Judah", summary: "", midrash: "", sources: "", image: null },
    { id: "yotam-ben-uziyahu", nameHe: "יותם בן עוזיהו", nameEn: "Jotham ben Uzziah", birthYear: 3167, deathYear: 3183, title: "King of Judah", summary: "", midrash: "", sources: "", image: null },
    { id: "achaz-ben-yotam", nameHe: "אחז בן יותם", nameEn: "Ahaz ben Jotham", birthYear: 3183, deathYear: 3199, title: "King of Judah", summary: "", midrash: "", sources: "", image: null },
    { id: "chizkiyahu-ben-achaz", nameHe: "חזקיהו בן אחז", nameEn: "Hezekiah ben Ahaz", birthYear: 3199, deathYear: 3228, title: "King of Judah", summary: "", midrash: "", sources: "", image: null },
    { id: "menashe-ben-chizkiyahu", nameHe: "מנשה בן חזקיהו", nameEn: "Manasseh ben Hezekiah", birthYear: 3228, deathYear: 3283, title: "King of Judah", summary: "", midrash: "", sources: "", image: null },
    { id: "yoshiyahu-ben-amon", nameHe: "יאשיהו בן אמון", nameEn: "Josiah ben Amon", birthYear: 3285, deathYear: 3316, title: "King of Judah", summary: "", midrash: "", sources: "", image: null },
    { id: "yehoyakim-ben-yoshiyahu", nameHe: "יהויקים בן יאשיהו", nameEn: "Jehoiakim ben Josiah", birthYear: 3316, deathYear: 3327, title: "King of Judah", summary: "", midrash: "", sources: "", image: null },
    { id: "tsidkiyahu-ben-yoshiyahu", nameHe: "צדקיהו מתניה בן יאשיהו", nameEn: "Zedekiah (Mattaniah) ben Josiah", birthYear: 3327, deathYear: 3338, title: "King of Judah", summary: "", midrash: "", sources: "", image: null }
  ],
  events: [
    { year: 2883, descHe: "מלכות דוד המלך", descEn: "Reign of King David" },
    { year: 2928, descHe: "בנין בית ראשון", descEn: "Building of the First Temple (dedicated; the Temple stood until 3338)" },
    { year: 2964, descHe: "התפלגות המלוכה", descEn: "Division of the kingdom" },
    { year: 3205, descHe: "גלות עשרת השבטים", descEn: "Exile of the Ten Tribes" },
    { year: 3336, descHe: "מצור על ירושלים", descEn: "Siege of Jerusalem" }
  ]
},
{
  id: "era-10-churban-bayit-rishon",
  nameHe: "חורבן בית ראשון",
  nameEn: "Destruction of the First Temple",
  startYear: 3338,
  endYear: 3448,
  persons: [
    { id: "gdalyahu-ben-achikam", nameHe: "גדליהו בן אחיקם", nameEn: "Gedaliah ben Ahikam", birthYear: 3338, deathYear: 3339, title: "Governor", summary: "", midrash: "", sources: "", image: null },
    { id: "achashverosh", nameHe: "אחשורוש", nameEn: "Ahasuerus (Xerxes)", birthYear: 3392, deathYear: 3406, title: "King", summary: "", midrash: "", sources: "", image: null },
    { id: "daryavesh-hasheni", nameHe: "דוריוש השני", nameEn: "Darius II", birthYear: 3406, deathYear: 3448, title: "King", summary: "", midrash: "", sources: "", image: null }
  ],
  events: [
    { year: 3338, descHe: "חרבן בית ראשון - גלות בבל", descEn: "Destruction of the First Temple — Babylonian exile" },
    { year: 3339, descHe: "גדליה נרצח", descEn: "Assassination of Gedaliah" },
    { year: 3364, descHe: "מות נבוכדנצר", descEn: "Death of Nebuchadnezzar" },
    { year: 3389, descHe: "מלכות דריוש המדי", descEn: "Reign of Darius the Mede" },
    { year: 3390, descHe: "מלכות פרס-כורש - גלות פרס", descEn: "Persian rule under Cyrus — Persian exile period" },
    { year: 3390, descHe: "הצהרת כורש ושיבת ציון", descEn: "Cyrus Declaration and return to Zion" },
    { year: 3405, descHe: "נס פורים", descEn: "Purim miracle" }
  ]
},
{
  id: "era-11-bayit-sheni",
  nameHe: "בית שני",
  nameEn: "Second Temple",
  startYear: 3408,
  endYear: 3462,
  persons: [
    { id: "shimon-ha-tzadik", nameHe: "שמעון הצדיק", nameEn: "Simeon the Just", birthYear: 3412, deathYear: 3462, title: "High Priest", summary: "", midrash: "", sources: "", image: null }
  ],
  events: [
    { year: 3408, descHe: "בנין בית שני", descEn: "Building of the Second Temple" },
    { year: 3415, descHe: "עלית עזרא הסופר", descEn: "Aliyah of Ezra the Scribe" },
    { year: 3442, descHe: "כיבוש אלכסנדר מוקדון", descEn: "Conquest by Alexander the Great (3442–3448)" },
    { year: 3442, descHe: "פטירת עזרא ונחמיה ונפסקה הנבואה", descEn: "Death of Ezra and Nehemiah; prophecy ceases" }
  ]
},
{
  id: "era-12-zugot",
  nameHe: "תקופת הזוגות",
  nameEn: "Period of the Pairs (Zugot)",
  startYear: 3500,
  endYear: 3768,
  persons: [
    { id: "yosei-ben-yoezer-v-yosef-ben-yochanan", nameHe: "יוסי בן יועזר ויוסף בן יוחנן", nameEn: "Jose ben Joezer and Joseph ben Johanan", birthYear: 3500, deathYear: 3560, title: "Zug (Pair)", summary: "", midrash: "", sources: "", image: null },
    { id: "yehoshua-ben-perachya-u-nitai-haarbeli", nameHe: "יהושע בן פרחיה וניתאי הארבלי", nameEn: "Joshua ben Perachiah and Nittai of Arbela", birthYear: 3560, deathYear: null, title: "Zug (Pair)", summary: "", midrash: "", sources: "", image: null },
    { id: "yehuda-ben-tabai-v-shimon-ben-shetach", nameHe: "יהודה בן טבאי ושמעון בן שטח", nameEn: "Judah ben Tabbai and Simeon ben Shetach", birthYear: 3621, deathYear: null, title: "Zug (Pair)", summary: "", midrash: "", sources: "", image: null },
    { id: "yehuda-hamakabi", nameHe: "יהודה המכבי", nameEn: "Judah the Maccabee", birthYear: 3622, deathYear: 3628, title: "Leader", summary: "", midrash: "", sources: "", image: null },
    { id: "yehonatan-hamakabi", nameHe: "יהונתן המכבי", nameEn: "Jonathan the Maccabee", birthYear: 3628, deathYear: 3634, title: "Leader", summary: "", midrash: "", sources: "", image: null },
    { id: "shimon-hamakabi", nameHe: "שמעון המכבי", nameEn: "Simeon the Maccabee", birthYear: 3634, deathYear: 3642, title: "Leader", summary: "", midrash: "", sources: "", image: null },
    { id: "yochanan-horkanos", nameHe: "יוחנן הורקנוס", nameEn: "John Hyrcanus", birthYear: 3642, deathYear: 3668, title: "Hasmonean King", summary: "", midrash: "", sources: "", image: null },
    { id: "shlomtzion-hamalka", nameHe: "שלומציון המלכה", nameEn: "Salome Alexandra (Shlomtzion)", birthYear: 3688, deathYear: 3697, title: "Queen", summary: "", midrash: "", sources: "", image: null },
    { id: "shmayah-v-avtalyon", nameHe: "שמעיה ואבטליון", nameEn: "Shemayah and Avtalyon", birthYear: 3722, deathYear: 3731, title: "Zug (Pair)", summary: "", midrash: "", sources: "", image: null },
    { id: "herodes", nameHe: "הורדוס", nameEn: "Herod", birthYear: 3724, deathYear: 3761, title: "King", summary: "", midrash: "", sources: "", image: null },
    { id: "hillel-v-shammai", nameHe: "הלל ושמאי", nameEn: "Hillel and Shammai", birthYear: 3731, deathYear: 3768, title: "Zug (Pair)", summary: "", midrash: "", sources: "", image: null }
  ],
  events: [
    { year: 3622, descHe: "נס חנוכה", descEn: "Hanukkah miracle" },
    { year: 3622, descHe: "מלכות בית חשמונאי", descEn: "Hasmonean dynasty (3622–3724)" }
  ]
},
{
  id: "era-13-tannaim",
  nameHe: "תקופת התנאים",
  nameEn: "Period of the Tannaim",
  startYear: 3760,
  endYear: 3833,
  persons: [
    { id: "rabbi-akiva", nameHe: "רבי עקיבא", nameEn: "Rabbi Akiva", birthYear: 3760, deathYear: 3880, title: "Tanna", summary: "", midrash: "", sources: "", image: null },
    { id: "rabban-shimon-ben-hillel", nameHe: "רבן שמעון בן הלל", nameEn: "Rabban Shimon ben Hillel", birthYear: 3768, deathYear: 3770, title: "Nasi", summary: "", midrash: "", sources: "", image: null },
    { id: "rabban-gamliel-hazaken", nameHe: "רבן גמליאל הזקן", nameEn: "Rabban Gamliel the Elder", birthYear: 3770, deathYear: 3810, title: "Nasi", summary: "", midrash: "", sources: "", image: null },
    { id: "rabban-shimon-ben-gamliel", nameHe: "רבן שמעון בן גמליאל", nameEn: "Rabban Shimon ben Gamliel", birthYear: 3810, deathYear: 3828, title: "Nasi", summary: "", midrash: "", sources: "", image: null },
    { id: "rabban-yochanan-ben-zakkai", nameHe: "רבן יוחנן בן זכאי", nameEn: "Rabban Yochanan ben Zakkai", birthYear: 3828, deathYear: 3833, title: "Tanna", summary: "", midrash: "", sources: "", image: null }
  ],
  events: []
},
{
  id: "era-14-churban-bayit-sheni",
  nameHe: "חורבן בית שני",
  nameEn: "Destruction of the Second Temple",
  startYear: 3828,
  endYear: 3979,
  persons: [
    { id: "rabban-gamliel-midia", nameHe: "רבן גמליאל השני דיבנה", nameEn: "Rabban Gamliel II of Yavneh", birthYear: 3833, deathYear: 3855, title: "Nasi", summary: "", midrash: "", sources: "", image: null },
    { id: "rabban-shimon-ben-gamliel-yavneh", nameHe: "רבן שמעון בן גמליאל", nameEn: "Rabban Shimon ben Gamliel", birthYear: 3880, deathYear: 3910, title: "Nasi", summary: "", midrash: "", sources: "", image: null },
    { id: "rabbi-yehuda-ha-nasi", nameHe: "רבי יהודה הנשיא", nameEn: "Rabbi Judah the Prince", birthYear: 3910, deathYear: 3979, title: "Nasi", summary: "", midrash: "", sources: "", image: null }
  ],
  events: [
    { year: 3828, descHe: "חרבן בית המקדש השני", descEn: "Destruction of the Second Temple" },
    { year: 3830, descHe: "נפילת מצדה", descEn: "Fall of Masada" },
    { year: 3855, descHe: "רבי עקיבא מנהיג", descEn: "Rabbi Akiva as leader (after Rabban Gamliel II)" },
    { year: 3878, descHe: "מרד בר כוכבא", descEn: "Bar Kokhba revolt (3878–3880)" },
    { year: 3880, descHe: "חרבן ביתר", descEn: "Destruction of Betar" },
    { year: 3880, descHe: "נהרג רבי עקיבא", descEn: "Martyrdom of Rabbi Akiva" },
    { year: 3979, descHe: "חתימת המשנה", descEn: "Redaction of the Mishnah" }
  ]
}
,
  {
    id: "era-15-amoraim-savoraim-geonim",
    nameHe: "תקופת האמוראים, סבוראים, גאונים",
    nameEn: "Period of the Amoraim, Savoraim, and Geonim",
    startYear: 3979,
    endYear: 4810,
    persons: [
      { id: "rav", nameHe: "רב", nameEn: "Rav (Abba Arikha)", birthYear: null, deathYear: 4007, title: "אמורא", summary: "", midrash: "", sources: "", image: null },
      { id: "shmuel", nameHe: "שמואל", nameEn: "Shmuel", birthYear: null, deathYear: 4014, title: "אמורא", summary: "", midrash: "", sources: "", image: null },
      { id: "rabbi-yohanan", nameHe: "רבי יוחנן", nameEn: "Rabbi Yoḥanan", birthYear: 3930, deathYear: 4039, title: "אמורא", summary: "", midrash: "", sources: "", image: null },
      { id: "rav-ashi", nameHe: "רב אשי", nameEn: "Rav Ashi", birthYear: 4120, deathYear: 4187, title: "אמורא", summary: "", midrash: "", sources: "", image: null },
      { id: "ravina", nameHe: "רבינא", nameEn: "Ravina", birthYear: null, deathYear: 4260, title: "אמורא", summary: "", midrash: "", sources: "", image: null },
      { id: "rav-achai-mishabcha", nameHe: "רב אחאי משבחא", nameEn: "Rav Aḥai of Shabḥa", birthYear: 4440, deathYear: 4512, title: "גאון", summary: "", midrash: "", sources: "", image: null },
      { id: "rav-sherira-gaon", nameHe: "רב שרירא גאון", nameEn: "Sherira Gaon", birthYear: 4666, deathYear: 4766, title: "גאון", summary: "", midrash: "", sources: "", image: null },
      { id: "rabbeinu-gershom", nameHe: "רבנו גרשום מאור הגולה", nameEn: "Rabbenu Gershom Meor HaGolah", birthYear: 4725, deathYear: 4800, title: "גאון", summary: "", midrash: "", sources: "", image: null },
      { id: "rav-hai-gaon", nameHe: "רב האי גאון", nameEn: "Rav Hai Gaon", birthYear: 4729, deathYear: 4798, title: "גאון", summary: "", midrash: "", sources: "", image: null },
      { id: "rabeinu-hananel", nameHe: "רבינו חננאל", nameEn: "Rabbenu Ḥananel", birthYear: 4740, deathYear: 4810, title: "גאון", summary: "", midrash: "", sources: "", image: null },
      { id: "rav-nissim-gaon", nameHe: "רב ניסים גאון", nameEn: "Rav Nissim Gaon", birthYear: 4760, deathYear: 4810, title: "גאון", summary: "", midrash: "", sources: "", image: null }
    ],
    events: [
      { year: 4039, descHe: "חתימת התלמוד הירושלמי", descEn: "Completion of the Jerusalem Talmud" },
      { year: 4261, descHe: "חתימת התלמוד הבבלי", descEn: "Completion of the Babylonian Talmud" },
      { year: 4349, descHe: "תחילת תקופת הגאונים (עד סביבות שנת ה׳ת״ר)", descEn: "Beginning of the Geonic period (until around 1040 CE)" }
    ]
  },
  {
    id: "era-16-rishonim",
    nameHe: "תקופת הראשונים",
    nameEn: "Period of the Rishonim",
    startYear: 4773,
    endYear: 5240,
    persons: [
      { id: "rif", nameHe: "הרי\"ף", nameEn: "Rif (Isaac Alfasi)", birthYear: 4773, deathYear: 4863, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "rashi", nameHe: "רש\"י", nameEn: "Rashi", birthYear: 4800, deathYear: 4865, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "rabbeinu-bachya", nameHe: "רבי בחיי", nameEn: "Rabbeinu Baḥya ibn Paquda", birthYear: 4810, deathYear: 4880, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "yehuda-halevi", nameHe: "רבי יהודה הלוי", nameEn: "Judah Halevi", birthYear: 4834, deathYear: 4901, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "ibn-ezra", nameHe: "רבי אברהם אבן עזרא", nameEn: "Abraham ibn Ezra", birthYear: 4849, deathYear: 4924, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "rabbeinu-tam", nameHe: "רבנו תם", nameEn: "Rabbenu Tam", birthYear: 4860, deathYear: 4931, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "rambam", nameHe: "הרמב\"ם", nameEn: "Maimonides (Rambam)", birthYear: 4895, deathYear: 4965, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "ramban", nameHe: "הרמב\"ן", nameEn: "Nachmanides (Ramban)", birthYear: 4954, deathYear: 5030, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "rabbi-yonah-gerondi", nameHe: "רבי יונה גירונדי", nameEn: "Jonah of Gerona", birthYear: 4960, deathYear: 5024, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "maharam-rothenburg", nameHe: "מהר\"ם מרוטנבורג", nameEn: "Meir of Rothenburg (Maharam)", birthYear: 4980, deathYear: 5053, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "rashba", nameHe: "הרשב\"א", nameEn: "Rashba (Solomon ibn Adret)", birthYear: 4995, deathYear: 5070, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "meiri", nameHe: "המאירי", nameEn: "Meiri", birthYear: 5009, deathYear: 5075, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "rosh", nameHe: "הרא\"ש", nameEn: "Rosh (Asher ben Yeḥiel)", birthYear: 5010, deathYear: 5085, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "ritva", nameHe: "הריטב\"א", nameEn: "Ritva (Yom Tov ibn Asevilli)", birthYear: 5010, deathYear: 5090, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "baal-haturim", nameHe: "רבי יעקב בן אשר", nameEn: "Jacob ben Asher (Ba'al ha-Turim)", birthYear: 5029, deathYear: 5103, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "ran", nameHe: "הר\"ן", nameEn: "Ran (Nissim of Gerona)", birthYear: 5080, deathYear: 5150, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "maharil", nameHe: "מהרי\"ל", nameEn: "Maharil (Jacob Moelin)", birthYear: 5115, deathYear: 5187, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "yitzchak-abuhav", nameHe: "רבי יצחק אבוהב", nameEn: "Isaac Abuhav", birthYear: 5143, deathYear: 5253, title: "ראשון", summary: "", midrash: "", sources: "", image: null },
      { id: "terumat-hadeshen", nameHe: "רבי יעקב בן משה מוילנא", nameEn: "Jacob ben Moses of Vienna (Terumat ha-Deshen)", birthYear: 5150, deathYear: 5220, title: "ראשון, בעל תרומת הדשן", summary: "", midrash: "", sources: "", image: null },
      { id: "maharik", nameHe: "מהרי\"ק", nameEn: "Maharik (Joseph Colon)", birthYear: 5180, deathYear: 5240, title: "ראשון", summary: "", midrash: "", sources: "", image: null }
    ],
    events: []
  },
  {
    id: "era-17-acharonim",
    nameHe: "תקופת האחרונים",
    nameEn: "Period of the Acharonim",
    startYear: 5200,
    endYear: 5774,
    persons: [
      { id: "avraham-zacuto", nameHe: "רבי אברהם זכות", nameEn: "Abraham Zacuto", birthYear: 5200, deathYear: 5275, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "ovadia-bartenura", nameHe: "רבי עובדיה מברטנורא", nameEn: "Obadiah of Bartenura", birthYear: 5205, deathYear: 5290, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "yosef-karo", nameHe: "רבי יוסף קארו", nameEn: "Joseph Karo (Beit Yosef, Shulḥan Arukh)", birthYear: 5248, deathYear: 5335, title: "אחרון, מרן, בעל השולחן ערוך", summary: "", midrash: "", sources: "", image: null },
      { id: "maharshal", nameHe: "מהרש\"ל", nameEn: "Maharshal (Solomon Luria)", birthYear: 5271, deathYear: 5334, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "maharal-prague", nameHe: "המהר\"ל מפראג", nameEn: "Maharal of Prague", birthYear: 5272, deathYear: 5369, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "rama", nameHe: "הרמ\"א", nameEn: "Rema (Moses Isserles)", birthYear: 5290, deathYear: 5333, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "ari-zal", nameHe: "האר\"י הקדוש", nameEn: "Isaac Luria (Arizal)", birthYear: 5294, deathYear: 5332, title: "אחרון, מקובל", summary: "", midrash: "", sources: "", image: null },
      { id: "maharhu", nameHe: "מהרח\"ו", nameEn: "Maharḥu (Ḥayim ben Bezalel)", birthYear: 5303, deathYear: 5380, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "maharsha", nameHe: "המהרש\"א", nameEn: "Maharsha (Samuel Edels)", birthYear: 5315, deathYear: 5391, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "shlah", nameHe: "השל\"ה הקדוש", nameEn: "Shlah (Isaiah Horowitz)", birthYear: 5320, deathYear: 5390, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "bach", nameHe: "הב\"ח", nameEn: "Bach (Joel Sirkis)", birthYear: 5321, deathYear: 5400, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "taz", nameHe: "הט\"ז", nameEn: "Taz (David Halevi Segal)", birthYear: 5346, deathYear: 5427, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "shach", nameHe: "הש\"ך", nameEn: "Shakh (Shabtai Cohen)", birthYear: 5383, deathYear: 5423, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "magen-avraham", nameHe: "מגן אברהם", nameEn: "Magen Avraham (Abraham Gombiner)", birthYear: 5397, deathYear: 5443, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "yonatan-eybeschutz", nameHe: "רבי יהונתן אייבשיץ", nameEn: "Jonathan Eybeschutz", birthYear: 5450, deathYear: 5524, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "shevet-yehuda", nameHe: "שאגת אריה", nameEn: "Sha'agat Aryeh (Aryeh Leib Gunzberg)", birthYear: 5455, deathYear: 5545, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "or-hachaim", nameHe: "אור החיים", nameEn: "Or ha-Ḥayim (Ḥayim ibn Attar)", birthYear: 5456, deathYear: 5503, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "ramchal", nameHe: "הרמח\"ל", nameEn: "Ramḥal (Moses Ḥayim Luzzatto)", birthYear: 5467, deathYear: 5507, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "baal-shem-tov", nameHe: "הבעש\"ט", nameEn: "Baal Shem Tov", birthYear: 5470, deathYear: 5520, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "nodeh-biyehuda", nameHe: "הנודע ביהודה", nameEn: "Noda bi-Yehuda (Yeḥezkel Landau)", birthYear: 5474, deathYear: 5553, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "elimelech-lizhensk", nameHe: "רבי אלימלך מליז'נסק", nameEn: "Elimelech of Lizhensk", birthYear: 5477, deathYear: 5547, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "gra-vilna", nameHe: "הגר\"א מוילנא", nameEn: "Vilna Gaon (Elijah of Vilna)", birthYear: 5480, deathYear: 5558, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "chida", nameHe: "החיד\"א", nameEn: "Ḥida (Ḥayim Joseph David Azulai)", birthYear: 5484, deathYear: 5566, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "baal-hatanya", nameHe: "בעל התניא", nameEn: "Shneur Zalman of Liadi (Baal ha-Tanya)", birthYear: 5505, deathYear: 5573, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "chozeh-lublin", nameHe: "החוזה מלובלין", nameEn: "Seer of Lublin (Jacob Isaac Horowitz)", birthYear: 5505, deathYear: 5575, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "chaim-volozhin", nameHe: "רבי חיים מוולוז'ין", nameEn: "Ḥayim of Volozhin", birthYear: 5509, deathYear: 5581, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "akiva-eger", nameHe: "רבי עקיבא איגר", nameEn: "Akiva Eger", birthYear: 5521, deathYear: 5598, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "chatam-sofer", nameHe: "החתם סופר", nameEn: "Ḥatam Sofer (Moses Sofer)", birthYear: 5523, deathYear: 5600, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "netivot", nameHe: "הנתיבות", nameEn: "Netivot (Jacob ben Jacob Moses Lorberbaum)", birthYear: 5530, deathYear: 5592, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "shlomo-kluger", nameHe: "רבי שלמה קלוגר", nameEn: "Solomon Kluger", birthYear: 5546, deathYear: 5629, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "menachem-mendel-kotzk", nameHe: "רבי מנחם מנדל מקוצק", nameEn: "Menachem Mendel of Kotzk", birthYear: 5547, deathYear: 5619, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "chaim-palagi", nameHe: "רבי חיים פלאג'י", nameEn: "Ḥayim Palaggi", birthYear: 5548, deathYear: 5628, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "tzemach-tzedek", nameHe: "הצמח צדק", nameEn: "Tzemach Tzedek (Menachem Mendel Schneersohn)", birthYear: 5549, deathYear: 5627, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "chidushei-harim", nameHe: "חידושי הרי\"ם", nameEn: "Ḥidushei ha-Rim (Isaac Meir Alter)", birthYear: 5559, deathYear: 5626, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "shimshon-raphael-hirsch", nameHe: "רבי שמשון רפאל הירש", nameEn: "Samson Raphael Hirsch", birthYear: 5568, deathYear: 5649, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "israel-salanter", nameHe: "רבי ישראל סלנטר", nameEn: "Israel Salanter", birthYear: 5570, deathYear: 5643, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "netziv", nameHe: "הנצי\"ב", nameEn: "Netziv (Naftali Zvi Berlin)", birthYear: 5577, deathYear: 5653, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "beit-halevi", nameHe: "בית הלוי", nameEn: "Beit Halevi (Joseph Soloveitchik of Brisk)", birthYear: 5580, deathYear: 5652, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "aruch-hashulchan", nameHe: "ערוך השולחן", nameEn: "Arukh ha-Shulḥan (Yechiel Michel Epstein)", birthYear: 5589, deathYear: 5668, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "ben-ish-chai", nameHe: "הבן איש חי", nameEn: "Ben Ish Ḥai (Joseph Ḥayim)", birthYear: 5595, deathYear: 5669, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "chafetz-chaim", nameHe: "החפץ חיים", nameEn: "Ḥafetz Ḥayim (Israel Meir Kagan)", birthYear: 5595, deathYear: 5693, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "or-sameach", nameHe: "אור שמח", nameEn: "Or Sameaḥ (Meir Simcha of Dvinsk)", birthYear: 5603, deathYear: 5686, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "sfas-emes", nameHe: "שפת אמת", nameEn: "Sfas Emes (Yehuda Aryeh Leib Alter)", birthYear: 5607, deathYear: 5665, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "chaim-soloveitchik-brisk", nameHe: "רבי חיים הלוי סולוביצ'יק", nameEn: "Ḥayim Soloveitchik of Brisk", birthYear: 5613, deathYear: 5678, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "rav-kook", nameHe: "הרב קוק", nameEn: "Abraham Isaac Kook", birthYear: 5625, deathYear: 5695, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "chazon-ish", nameHe: "החזון איש", nameEn: "Ḥazon Ish (Abraham Yeshayahu Karelitz)", birthYear: 5639, deathYear: 5714, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "yehezkel-levenstein", nameHe: "רבי יחזקאל לוינשטיין", nameEn: "Yeḥezkel Levenstein", birthYear: 5645, deathYear: 5734, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "baba-sali", nameHe: "בבא סאלי", nameEn: "Baba Sali (Israel Abuhatzeira)", birthYear: 5650, deathYear: 5744, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "moshe-feinstein", nameHe: "רבי משה פינשטיין", nameEn: "Moshe Feinstein", birthYear: 5655, deathYear: 5746, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "yitzchak-kaduri", nameHe: "רבי יצחק כדורי", nameEn: "Yitzḥak Kaduri", birthYear: 5656, deathYear: 5766, title: "אחרון, מקובל", summary: "", midrash: "", sources: "", image: null },
      { id: "elazar-menachem-shach", nameHe: "רבי אלעזר מנחם מן שך", nameEn: "Elazar Menachem Man Shach", birthYear: 5659, deathYear: 5762, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "rebbe-lubavitch", nameHe: "הרבי מלובביץ", nameEn: "The Lubavitcher Rebbe (Menachem Mendel Schneerson)", birthYear: 5662, deathYear: 5754, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "shlomo-zalman-auerbach", nameHe: "רבי שלמה זלמן אוירבך", nameEn: "Shlomo Zalman Auerbach", birthYear: 5670, deathYear: 5755, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "yosef-shalom-elyashiv", nameHe: "רבי יוסף שלום אלישיב", nameEn: "Yosef Shalom Elyashiv", birthYear: 5670, deathYear: 5772, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "ovadia-yosef", nameHe: "רבי עובדיה יוסף", nameEn: "Ovadia Yosef", birthYear: 5681, deathYear: 5774, title: "אחרון, מרן", summary: "", midrash: "", sources: "", image: null },
      { id: "mordechai-eliyahu", nameHe: "רבי מרדכי אליהו", nameEn: "Mordechai Eliyahu", birthYear: 5689, deathYear: 5770, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "yaakov-emden", nameHe: "רבי יעקב עמדן", nameEn: "Jacob Emden", birthYear: 5513, deathYear: 5593, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "yitzchak-elchanan-spector", nameHe: "רבי יצחק אלחנן ספורק", nameEn: "Isaac Elhanan Spector", birthYear: 5580, deathYear: 5652, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "chaim-ozer-grodzenski", nameHe: "רבי חיים עוזר גרודזנסקי", nameEn: "Ḥayim Ozer Grodzenski", birthYear: 5630, deathYear: 5704, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "isser-zalman-meltzer", nameHe: "רבי איסר זלמן מלצר", nameEn: "Isser Zalman Meltzer", birthYear: 5688, deathYear: 5732, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "elchanan-wasserman", nameHe: "רבי אלחנן וסרמן", nameEn: "Elchonon Wasserman", birthYear: 5634, deathYear: 5701, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "aharon-kotler", nameHe: "רבי אהרן קוטלר", nameEn: "Aharon Kotler", birthYear: 5651, deathYear: 5722, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "meir-shapiro", nameHe: "רבי מאיר שפירא", nameEn: "Meir Shapiro", birthYear: 5647, deathYear: 5693, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "yaakov-kamenetsky", nameHe: "רבי יעקב קמינצקי", nameEn: "Yaakov Kamenetsky", birthYear: 5641, deathYear: 5746, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "yoel-teitelbaum", nameHe: "רבי יואל טייטלבוים", nameEn: "Joel Teitelbaum of Satmar", birthYear: 5657, deathYear: 5739, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "moshe-mordechai-epstein", nameHe: "רבי משה מרדכי אפשטיין", nameEn: "Moses Mordechai Epstein", birthYear: 5677, deathYear: 5738, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "baruch-ber-leibowitz", nameHe: "רבי ברוך בער לייבוביץ", nameEn: "Baruch Ber Leibowitz", birthYear: 5620, deathYear: 5700, title: "אחרון", summary: "", midrash: "", sources: "", image: null },
      { id: "isser-yehuda-unterman", nameHe: "רבי ישראל יהודה אונטרמן", nameEn: "Isser Yehuda Unterman", birthYear: 5676, deathYear: 5736, title: "אחרון", summary: "", midrash: "", sources: "", image: null }
    ],
    events: []
  }
];
